# Generated by Django 4.2.5 on 2023-10-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=25)),
                ('telefono', models.IntegerField(max_length=8)),
                ('f_nacimiento', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
